### ISSUE TITLE
getting started - db seeding. 

### ISSUE THREAD

**Issue by johndpope** [bobderrico80/rhythmrandomizer#1]
I fired up MAMP - changed the connections strings / added the database
![Uploading Screen Shot 2015-01-24 at 4.57.35 pm.png . . .]()

pointed the root folder to your rhythm folder
![screen shot 2015-01-24 at 4 57 53 pm](https://cloud.githubusercontent.com/assets/289994/5886281/39d36d0c-a3ea-11e4-9753-e418b4afd5b0.png)

but It's not seeding the database. 
Can you please include the database file so I can plug this in ? 
Or provide a sql script to create tables +  input some values ?

Thx in advance

**Comment by bobderrico80** [comment]
I've updated the `README.md` file to include the SQL necessary to set up the database. You should be able to import this into PHPMyAdmin, and be up-and-running.
